### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by Filip-H** [Inventorum-Development-Team/IDT_XCOM_Reach#2]
- [ ] reduced moraleLossWhenKilledfor grunts
- [x] gaps in pelican and droppod walls
- [x] units can't leave droppods on map edge
- [x] pelican door on wrong wall
- [x] reduce grenades
- [ ] reduce grenades that were reintroduced in branch merge
- [x] Final missions reinforcements friendly
- [ ] Rebalance air combat?
- [ ] Rebalance sellcosts
- [ ] Rebalance score
- [x] Check stealth values on Armor
- [ ] BR burst stats too similar
- [ ] medikit sprite not centered, (or reduce size)
- [ ] Grenade ufopedia
- [ ] cooldowns for armor abilities on ufopedia pages
- [ ] Base build cost 0
- [ ] consider no hitanimation on some weapons
- [ ] supercombining script
- [ ] Elerium name
- [ ] reduce knife damage
- [ ] Disable ability slot for non-spartans
- [ ] test fuel rod damage
- [ ] No arc on fuel rod?
- [ ] defeat slideshow text cut off
- [ ] Reduce elite shields
